<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**
* @var $block \Emipro\Custompayment\Block\Info\Custompayment
 */

?>

<dl class="payment-method custompayment">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getInfo()->getAdditionalInformation()): ?>
        <?php if ($block->getPayableTo()): ?>
            <dd class="content">
                <strong><?= $block->escapeHtml(__('Make Check payable to')) ?></strong>
                <?= $block->escapeHtml($block->getPayableTo()) ?>
          
            </dd>
                 
        <?php endif; ?>
    
    <?php endif; ?>
</dl>