<?php
/**

 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**
 * @var $block \Emipro\Custompayment\Block\Form\Custompayment
 */

<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" style="display:none">
    <?php if ($block->getMethod()->getPayableTo()): ?>
        <label class="label"><span><?= $block->escapeHtml(__('Make Check payable to:')) ?></span></label> <?= $block->escapeHtml($block->getMethod()->getPayableTo()) ?>
        
    <?php endif; ?>
 
</fieldset>