<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**
 * @var $block \Emipro\Custompayment\Block\Form\Custompayment
 */

?>
<?php if ($block->getMethod()->getMailingAddress() || $block->getMethod()->getPayableTo()): ?>
    <dl class="items check payable" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" >
        <?php if ($block->getMethod()->getPayableTo()): ?>
            <dt class="title"><?= $block->escapeHtml(__('Make Check payable to:')) ?></dt>
            <dd class="content"><?= $block->escapeHtml($block->getMethod()->getPayableTo()) ?></dd>
        
          

        <?php endif; ?>
       
    </dl>
<?php endif; ?>